### ISSUE TITLE
from scapy.all import *  does not work

### ISSUE THREAD

**Issue by BruceTing** [phaethon/kamene#167]
python version is 3.6.1
and I use this command install scapy: pip install scapy-python3
when I run: from scapy.all import *
I get this:
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from scapy.all import *
  File "D:\Devenv\python36\lib\site-packages\scapy\all.py", line 16, in <module>
    from .arch import *
  File "D:\Devenv\python36\lib\site-packages\scapy\arch\__init__.py", line 95, in <module>
    from .windows import *
  File "D:\Devenv\python36\lib\site-packages\scapy\arch\windows\__init__.py", line 23, in <module>
    from scapy.arch import pcapdnet
  File "D:\Devenv\python36\lib\site-packages\scapy\arch\pcapdnet.py", line 32, in <module>
    from .winpcapy import *
  File "D:\Devenv\python36\lib\site-packages\scapy\arch\winpcapy.py", line 26, in <module>
    _lib=CDLL('wpcap.dll')
  File "D:\Devenv\python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126]

so, how can i fix it ???

**Comment by kos08001** [comment]
Did you find a solution? I'm getting the same issue.

**Comment by BruceTing** [comment]
yes, it works when i installed **winpcap**

**Comment by gpotter2** [comment]
Hi !

This issue has been resolved on the original scapy fork, which now supports Python 3 !
This fork (scapy3k) is missing many updates, bug fixes and tweaks. You can have a look at
https://github.com/secdev/scapy to get more support !

Have a good day

**Comment by DK-denno** [comment]
I am also getting the same error "no module named scapy.all."and" scapy is not a package"

**Comment by phaethon** [comment]
Are you using pip package or git? Did you notice that the package was renamed meanwhile?
